#!/usr/bin/env bash
# Script didatico: automatiza configuracao de servidor, Nginx, DNS ou SSL para a SIX.
set -euo pipefail

DOMAIN="${1:-www.xis.com.br}"
SERVER_IP="${2:-}"
PROJECT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
NODE_BIN="$(command -v node || true)"


# Algumas alteracoes mexem em /etc, systemd ou Nginx, por isso precisam de sudo/root.
if [ "$(id -u)" -ne 0 ]; then
  echo "Execute como root: sudo bash deploy/ubuntu-intranet-setup.sh ${DOMAIN} [IP_DO_SERVIDOR]"
  exit 1
fi

if [ -z "${SERVER_IP}" ]; then
  SERVER_IP="$(hostname -I | awk '{print $1}')"
fi

if [ -z "${SERVER_IP}" ]; then
  echo "Nao consegui detectar o IP do servidor. Informe manualmente:"
  echo "sudo bash deploy/ubuntu-intranet-setup.sh ${DOMAIN} 192.168.0.188"
  exit 1
fi

if [ -z "${NODE_BIN}" ]; then
  echo "Node.js nao encontrado. Instale Node.js 24+ antes de continuar."
  echo "Depois rode novamente este script."
  exit 1
fi

NODE_MAJOR="$(${NODE_BIN} -p 'Number(process.versions.node.split(".")[0])')"
if [ "${NODE_MAJOR}" -lt 24 ]; then
  echo "Node.js 24+ e necessario. Versao atual: $(${NODE_BIN} -v)"
  exit 1
fi

echo "Projeto SIX: ${PROJECT_DIR}"
echo "Dominio local: ${DOMAIN}"
echo "IP do servidor: ${SERVER_IP}"


# Instala pacotes do Ubuntu necessarios para proxy, DNS ou certificados.
apt-get update
DEBIAN_FRONTEND=noninteractive apt-get install -y nginx dnsmasq curl

cd "${PROJECT_DIR}"
if [ ! -f .env ]; then
  cp .env.example .env
fi
mkdir -p data


# Atualiza ou cria uma chave no .env sem duplicar linhas.
set_env() {
  local key="$1"
  local value="$2"
  if grep -q "^${key}=" .env; then
    sed -i "s|^${key}=.*|${key}=${value}|" .env
  else
    printf '\n%s=%s\n' "${key}" "${value}" >> .env
  fi
}

set_env SIX_HOST 127.0.0.1
set_env SIX_PORT 3000
set_env SIX_ALLOWED_EMAIL_DOMAINS educacao.sp.gov.br,professor.educacao.sp.gov.br
set_env SIX_COOKIE_SECURE false


# Cria o servico systemd para manter o Node.js rodando em segundo plano.
cat >/etc/systemd/system/six.service <<SERVICE
[Unit]
Description=SIX Intranet
After=network.target

[Service]
Type=simple
WorkingDirectory=${PROJECT_DIR}
ExecStart=${NODE_BIN} src/server.js
Restart=always
RestartSec=3
Environment=NODE_ENV=production

[Install]
WantedBy=multi-user.target
SERVICE

systemctl daemon-reload
systemctl enable --now six


# Escreve a configuracao do Nginx que encaminha o dominio para o Node.js.
cat >/etc/nginx/sites-available/six.conf <<NGINX
server {
    listen 80;
    server_name ${DOMAIN};

    client_max_body_size 10m;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/six.conf /etc/nginx/sites-enabled/six.conf
nginx -t
systemctl enable --now nginx
systemctl reload nginx

cat >/etc/dnsmasq.d/six-local.conf <<DNSMASQ
# SIX local DNS
# Generated by deploy/ubuntu-intranet-setup.sh
listen-address=127.0.0.1,${SERVER_IP}
bind-interfaces
address=/${DOMAIN}/${SERVER_IP}
server=1.1.1.1
server=8.8.8.8
DNSMASQ

systemctl enable --now dnsmasq
systemctl restart dnsmasq


# Se o firewall UFW estiver ativo, libera as portas necessarias.
if command -v ufw >/dev/null 2>&1 && ufw status | grep -q "Status: active"; then
  ufw allow 80/tcp
  ufw allow 53/tcp
  ufw allow 53/udp
fi

sleep 2
curl -fsS http://127.0.0.1:3000/api/config >/dev/null
curl -fsS -H "Host: ${DOMAIN}" http://127.0.0.1/ >/dev/null

echo
printf 'OK. SIX configurada para http://%s\n' "${DOMAIN}"
printf 'Servidor DNS local: %s\n' "${SERVER_IP}"
echo
echo "Agora configure o roteador Mercury/Mercusys:"
echo "1. Reserve/fixe o IP deste Ubuntu Server: ${SERVER_IP}"
echo "2. Em DHCP Server, coloque DNS primario: ${SERVER_IP}"
echo "3. Reconecte os aparelhos ao Wi-Fi ou reinicie o roteador."
echo "4. Acesse: http://${DOMAIN}"